# Generated by Django 3.2.13 on 2023-03-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=5, verbose_name='Resultado de cálculo de IMC')),
            ],
            options={
                'verbose_name': 'Imc',
                'verbose_name_plural': 'Imcs',
            },
        ),
    ]
